blank_issues_enabled: false
contact_links:
  - name: ğŸ˜ Contribution Guide
    url: https://github.com/iamkhattar/homelab/blob/master/.github/CONTRIBUTING.md
    about: Please read through before making any contribution.
